var data = {
	"snow":{
		"src":"http://cranberrycinnamon.com/Kevin/WEB/weather/snow/SnowFall.html",
		"code":"",
		"info":"This was one of the first pieces of javascript code I wrote working with the canvas. Its just a simple representation of animating snow. ",
		"input":"Move: A & D; 	 Jump: Space;",
		"link1":"",
		"link2":"",
		"link3":"",
		"link1innerHTML":"",
		"link2innerHTML":"",
		"link3innerHTML":"",
		"title":"snow",
	},
	"leaf":{
		"src":"http://cranberrycinnamon.com/Kevin/WEB/weather/leaves/LeafFall.html",
		"code":"",
		"info":"Leaf is a part of a weather collection I am making. It is my take on how leaves fall. ",
		"input":"",
		"link1":"",
		"link2":"",
		"link3":"",
		"link1innerHTML":"",
		"link2innerHTML":"",
		"link3innerHTML":"",
		"title":"leaf",
	}, 
	"paulbunyan":{
		"src":"http://www.whaleblubber.net/Kevin/html/paulbunyan/",
		"code":"https://github.com/Levo/Pixi-Js/tree/master/Paul",
		"info":"This game was created for Public Domain Jam // 2014. It was one week of development.",
		"input":"Move: A & D & S & W; 	 Fire: LeftMouse;",
		"link1":"http://itch.io/jam/the-public-domain-jam",
		"link2":"",
		"link3":"",
		"link1innerHTML":"Public Domain game Jam Article",
		"link2innerHTML":"",
		"link3innerHTML":"",
		"title":"Paul Bunyan",
	},
	"bleuetrouge":{
		"src":"http://www.whaleblubber.net/Kevin/html/bleuetrouge",
		"code":"",
		"info":"I created this game for Clay.io's Got Game? competition // 2014. It was one month of development and a two week judging process. I placed 4th and won a Nexus 7.",
		"input":"",
		"link1":"http://www.waubonsee.edu/news/archive/2014/20140620VideoGameDesignContestNadro.php",
		"link2":"http://clay.io/blog/announcing-the-got-game-2014-winners/",
		"link3":"http://clay.io/gotgame",
		"link1innerHTML":"News Article",
		"link2innerHTML":"Got Game? Winners - blog post",
		"link3innerHTML":"Competition details",
		"title":"Bleu et Rouge",
	},
	"dungeon":{
		"src":"http://www.whaleblubber.net/Kevin/html/totych",
		"code":"",
		"info":"I used imapactJS to implement the random dungeon generator.",
		"input":"Move: W & A & S & D",
		"link1":"",
		"link2":"",
		"link3":"",
		"link1innerHTML":"",
		"link2innerHTML":"",
		"link3innerHTML":"",
		"title":"Dungeon",
	},
	"astar":{
		"src":"http://cranberrycinnamon.com/Kevin/WEB/A*/astar.html",
		"code":"https://github.com/Levo/A-Star",
		"info":"I created this A* pathfinding program to show it implemented in javascript.",
		"input":"Click to place walls & Nodes;		Press Enter to Continue",
		"link1":"",
		"link2":"",
		"link3":"",
		"link1innerHTML":"",
		"link2innerHTML":"",
		"link3innerHTML":"",
		"title":"A*",
	},
	"gameboy":{
		"src":"http://cranberrycinnamon.com/Kevin/WEB/gameboy",
		"code":"",
		"info":"This game was created for a gameboy game jam on game jolt. The objective is to collect the 5 coins on each level.",
		"input":"Move: W & A & S & D;		Fire: LeftMouse;		SwitchWeapons: Q",
		"link1":"http://jams.gamejolt.io/gbjam3",
		"link2":"",
		"link3":"",
		"link1innerHTML":"Game Jolt",
		"link2innerHTML":"",
		"link3innerHTML":"",
		"title":"Gameboy",
	},
	"raycast":{
		"src":"http://cranberrycinnamon.com/Kevin/WEB/raycasting/raycast.html",
		"code":"https://github.com/Levo/raycasting",
		"info":"I found a tutorial on how to implement raycasting and ported it to javascript",
		"input":"Move: W & A & S & D",
		"link1":"http://lodev.org/cgtutor/raycasting.html",
		"link2":"",
		"link3":"",
		"link1innerHTML":"Lode's Raycasting Tutorial",
		"link2innerHTML":"",
		"link3innerHTML":"",
		"title":"raycast",
	},
	"maze":{
		"src":"http://cranberrycinnamon.com/Kevin/WEB/Maze/maze.html",
		"code":"https://github.com/Levo/Maze",
		"info":"Randomly generate different size mazes!",
		"input":"",
		"link1":"",
		"link2":"",
		"link3":"",
		"link1innerHTML":"",
		"link2innerHTML":"",
		"link3innerHTML":"",
		"title":"maze",
	},
	"graph":{
		"src":"http://cranberrycinnamon.com/Kevin/WEB/Graph/graph.html",
		"code":"https://github.com/Levo/Graph",
		"info":"A graph application that allows you to create a graph structure to run different algorithms.",
		"input":"",
		"link1":"",
		"link2":"",
		"link3":"",
		"link1innerHTML":"",
		"link2innerHTML":"",
		"link3innerHTML":"",
		"title":"graph",
	},
	"dither":{
		"src":"http://cranberrycinnamon.com/Kevin/WEB/dither/dither.html",
		"code":"https://github.com/Levo/dither",
		"info":"Floyd-Stienberg dithering.",
		"input":"",
		"link1":"",
		"link2":"",
		"link3":"",
		"link1innerHTML":"",
		"link2innerHTML":"",
		"link3innerHTML":"",
		"title":"dither",
	},
	"lsystem":{
		"src":"http://cranberrycinnamon.com/Kevin/WEB/lsystem/index.html",
		"code":"https://github.com/Levo/L-S",
		"info":"L systems",
		"input":"",
		"link1":"",
		"link2":"",
		"link3":"",
		"link1innerHTML":"",
		"link2innerHTML":"",
		"link3innerHTML":"",
		"title":"L System",
	},
	"curve":{
		"src":"http://cranberrycinnamon.com/Kevin/WEB/curves/curves.html",
		"code":"https://github.com/Levo/curves",
		"info":"Bezier curve",
		"input":"",
		"link1":"",
		"link2":"",
		"link3":"",
		"link1innerHTML":"",
		"link2innerHTML":"",
		"link3innerHTML":"",
		"title":"bezier curve",
	},
	"turtle3d":{
		"src":"http://cranberrycinnamon.com/Kevin/WEB/turtle3D/",
		"code":"https://github.com/Levo/turtle3D",
		"info":"3D L-System with turtle graphics. I have it drawing a 3D hilbert curve.",
		"input":"W,S : move forward; A,D: roll; Up,Down arrow: pitch;",
		"link1":"",
		"link2":"",
		"link3":"",
		"link1innerHTML":"",
		"link2innerHTML":"",
		"link3innerHTML":"",
		"title":"3D L System",
	},
	"cs445":{
		"src":"",
		"code":"",
		"info":"I took CS 445: Computational Photography (Fall 2015) @ UIUC with Derek Hoiem. Currently my most favorite course taken at UIUC (thanks Derek). Here is a list of the projects I completed in this course.",		
		"title":"CS 445: Computational Photography",
	}


	// https://courses.engr.illinois.edu/cs445/



};