var JSONObject = {
	"snow":{
		"src":"http://www.whaleblubber.net/Kevin/html/snow/SnowFall.html",
		"code":"https://github.com/Levo/DisplayMyExamples/tree/master/SnowFall",
		"info":"Snow is one part of a weather collection I am creating.  My goal is to create different weather types in javascript",
	},
	"leaf":{
		"src":"http://www.whaleblubber.net/Kevin/html/leaf/LeafFall.html",
		"code":"https://github.com/Levo/DisplayMyExamples/tree/master/LeafFall",
		"info":""
	},
	"rain":{
		"src":"http://www.whaleblubber.net/Kevin/html/rain/RainFall.html",
		"code":"https://github.com/Levo/DisplayMyExamples/tree/master/RainFall",
		"info":"",
	},
	"paulbunyan":{
		"src":"http://www.whaleblubber.net/Kevin/html/paulbunyan/",
		"code":"https://github.com/Levo/Pixi-Js/tree/master/Paul",
		"info":"",
	},
	"coloredsquares":{
		"src":"http://www.whaleblubber.net/Kevin/html/coloredsquares/ColorSquare.html",
		"code":"https://github.com/Levo/ColoringSquares",
		"info":"",
	},
	"bleuetrouge":{
		"src":"http://www.whaleblubber.net/Kevin/html/bleuetrouge",
		"code":"",
		"info":"",
	},
	"bullethell":{
		"src":"http://www.whaleblubber.net/Kevin/html/bullethell/BulletHell.html",
		"code":"https://github.com/Levo/DisplayMyExamples/tree/master/BulletHell",
		"info":"",
	},
	"rundodge":{
		"src":"http://www.whaleblubber.net/Kevin/html/rundodge/SpeedRun.html",
		"code":"https://github.com/Levo/DisplayMyExamples/tree/master/Threejs",
		"info":"",
	}
};